<?php
unset($_SESSION['nueva_familia']);
?>
<!doctype html>
<html>
	<title>Bienvenido a SIGAF</title>
<head>
	<meta charset="utf-8" />
	<link rel='stylesheet' type='text/css' href='views/css/bienvenida.css'/>
</head>
<body>
<div id='general' style='border:1px solid #000; width:280px; background:#fff; padding:5px;'>
<center><b><?php echo $tema; ?></b></center>
<BR>

<div style='text-align:center; '>

<label style='font-weight:bold;'>Versión del producto:</label><br> 1.0 BETA
<br>
<br>
<label style='font-weight:bold;'>Desarrollado por:</label><br>
Miguel Salazar<br>
2014
<br><br>
<label style='font-weight:bold;'>Licencia:</label><br>
En proceso de registro
</div>

</div>
</body>
</html>

