<?php 
if($_SESSION['nivel_usuario']=='Administrador')
{
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<title><?php echo $tema; ?></title>
			<script type='text/javascript' src='views/js/funciones.js'></script>
			<link rel='stylesheet' type='text/css' href='views/css/mensajes_validacion.css'/>
			<link rel="stylesheet" href="views/css/pickmeup.css" type="text/css" />
			<script type="text/javascript" src="views/js/jquery.js"></script>
			<script type="text/javascript" src="views/js/jquery.pickmeup.js"></script>
			<script type="text/javascript" src="views/js/demo.js"></script>
			<link rel="stylesheet" type="text/css" href="views/css/estilo_formularios.css" />
	</head>
<body>
<?php
$finanza=$objLibroMayor->consultarOperacion();
for($i=0;$i<count($finanza);$i++)
	{
	if($finanza[$i]['tipo_op']=='Ingreso')
		$ingreso+=$finanza[$i]['monto'];
	else
		$egreso+=$finanza[$i]['monto'];
	$subTotal+=$finanza[$i]['monto'];
	$saldo=$ingreso-$egreso;
	}
$mostrarFormulario=true;
//Validando del lado del servidor
if(isset($_POST['enviar']))
	{
	if(empty($_POST['comprobante']))
		echo $mensaje['not_comp'];
	else if(empty($_POST['tipo_op']))
		echo $mensaje['not_code'];
	else if(empty($_POST['monto']))
		echo $mensaje['not_mount'];
	else if($saldo<$_POST['monto']&&$_POST['tipo_op']=='Egreso')
		echo $mensaje['error_mount'];
	else if(empty($_POST['fecha_comp']))
		echo $mensaje['not_date'];
	else if(empty($_POST['descripcion']))	
		echo $mensaje['not_descrition'];	
//fin validación					
	else
		{
		$fecha=explode('-',$_POST['fecha_comp']);
		//Registrando operación a la base de datos
		$res=$objLibroMayor->agregarOperacion($_POST['comprobante'],$_POST['tipo_op'],$_POST['descripcion'],$_POST['monto'],$fecha[2].'-'.$fecha[1].'-'.$fecha[0]);
		if($res)
			//Registrando acción realizada
			Historial::Movimiento($_SESSION['tipo_op'],"Registró operación financiera: <b>".$_POST['comprobante']."</b>");
		$mostrarFormulario=false;
		}
	}
//Mostrando formulario de registro
if($mostrarFormulario)
{
?>
<div class='tema'><p><?php echo $tema; ?></p></div>

<form id="form" name="form" method="POST" action="">
<table class='principal' cellspacing='15px' border='0'> 
			<tr>
				<td>N° de comprobante:<br>	
					<input class='input' value='<?php if(!empty($_POST['comprobante'])) echo $_POST['comprobante']; ?>' type='text'  maxlength='12' name='comprobante' id='comprobante' class='input' onKeyPress='return validaSoloNumero(event);'>
				</td>
		
				<td>Tipo de operación:<br>	
					<input <?php if($_POST['tipo_op']=='Ingreso') { ?>checked<?php } ?> type='radio' value='Ingreso' name='tipo_op' id='tipo_op' class='radio'> Ingreso
					<input <?php if($_POST['tipo_op']=='Egreso') { ?>checked<?php } ?> type='radio' value='Egreso' name='tipo_op' id='tipo_op' class='radio'> Engreso
				</td>
			<tr>
			</tr>
				<td>Monto (Bs.):<br>
					<input class='input'  value='<?php if(!empty($_POST['monto'])) echo $_POST['monto']; ?>' type='text' maxlength='50' name='monto' id='monto' onKeyPress='return validaNumero(event);' placeholder='Ej. 999.99'>
				</td>	
				<td>Fecha del comprobante:<br>
					<input readonly value="<?php if(!empty($_POST['fecha_comp'])) echo $_POST['fecha_comp']; ?>" type='text' name='fecha_comp' class='datepicker' size="20" placeholder='dd-mm-aaaa'/>
				</td>						
			</tr>
			<tr>
				<td colspan='2'>Descrip:ción:<BR>
				<textarea name='descripcion' style='resize:none; height:40px; width:295px;' maxlength='80'><?php if(!empty($_POST['descripcion'])) echo $_POST['descripcion']; ?></textarea>	

				</td>
			</tr>
			<tr style='text-align:center;'>
				<td colspan='2' ><br>
					<input class='boton_left' type='reset' value='Limpiar'>
					<input class='boton_right' type='submit' name='enviar' value='Registrar'>
				</td>
			</tr>
		</table>
</form>
<?php
//Fin de mostrar formulario
}if(isset($res))
	{
	if($res)
		{
		echo $mensaje['registered'];
		header("refresh:2;url=?opcion=inicio");
		}
	else
		{
		echo $mensaje['error_registered'];
		header("refresh:2;url=?opcion=inicio");			
		}
	}
?>
</body>
</html>
<?php
}
else
	echo $mensaje['not_acces'];
?>
