<?php
unset($_SESSION['nueva_familia']);
?>
<!doctype html>
<html>
	<title>Bienvenido a SIGAF</title>
<head>
	<meta charset="utf-8" />
	<link rel='stylesheet' type='text/css' href='views/css/bienvenida.css'/>
</head>
<body>
<div id='general'>
<center><b>..::Bienvenido al Sistema de Gestión Administrativa y Financiera::..</b></center>
<BR>

<label style='text-align:justify;'>
<p>
La aplicación se basa en el mejoramiento socio productivo y económico de la comunidad “Punta Brava, La Poza y Los Primos”, debido a que los procesos administrativos y financieros se automatizan con tal motivo de ofrecer un óptimo funcionamiento y lograr obtener un margen de error mínimo en las labores ejercidas. Mediante el uso adecuado de esta herramienta, se fortalece en diferentes aspectos a la comunidad,  porque se lográn tomar las mejores decisiones en conjunto, y así conseguir resultados que sean beneficiosos para todos.
</p>

<p>
Un sistema basado en tecnologías libres y estándares abiertos, con la ventaja de que pueda ser usado, estudiado, mejorado y quizá distribuido, con fines positivos para la nación.  Al mismo tiempo cabe señalar que se avanza tecnológicamente apoyando al Plan Nacional de Ciencia y Tecnología.					       			 
</p>
</div>
</body>
</html>

