<?php
session_start();
?>

<input type='hidden' id='en_espera' value="<?php echo $_GET['en_espera']; ?>">
<input type='hidden' id='aprobados' value="<?php echo $_GET['aprobados']; ?>">
<input type='hidden' id='no_aprobados' value="<?php echo $_GET['no_aprobados']; ?>">
<input type='hidden' id='en_elaboracion' value="<?php echo $_GET['en_elaboracion']; ?>">
<input type='hidden' id='finalizados' value="<?php echo $_GET['finalizados']; ?>">
<input type='hidden' id='no_finalizados' value="<?php echo $_GET['no_finalizados']; ?>">
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    
    <head>
        <meta charset="utf-8">
        <title><?php echo $tema; ?></title>
        <script src="libs/amcharts/amcharts/amcharts.js" type="text/javascript"></script>
        <script src="libs/amcharts/amcharts/pie.js" type="text/javascript"></script>
        <link rel='stylesheet' type='text/css' href='views/css/consultar.css'/>
        <script type="text/javascript">
            var chart;
            var legend;
            var en_espera=document.getElementById('en_espera').value;
            var aprobados=document.getElementById('aprobados').value;
            var no_aprobados=document.getElementById('no_aprobados').value;
            var en_elaboracion=document.getElementById('en_elaboracion').value;
            var finalizados=document.getElementById('finalizados').value;
            var no_finalizados=document.getElementById('no_finalizados').value;
            var chartData = [{
                country: "En espera",
                litres: en_espera
            }, {
                country: "Aprobados",
                litres: aprobados
            }, {
                country: "No aprobados",
                litres: no_aprobados
            }, {
                country: "En ejecución",
                litres: en_elaboracion
            }, {
                country: "Finalizados",
                litres: finalizados
            }];

            AmCharts.ready(function () {
                // PIE CHART
                chart = new AmCharts.AmPieChart();
                chart.dataProvider = chartData;
                chart.titleField = "country";
                chart.valueField = "litres";

                // LEGEND
                legend = new AmCharts.AmLegend();
                legend.align = "center";
                legend.markerType = "circle";
                chart.balloonText = "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>";
                chart.addLegend(legend);

                // WRITE
                chart.write("chartdiv");
            });

            // changes label position (labelRadius)
            function setLabelPosition() {
                if (document.getElementById("rb1").checked) {
                    chart.labelRadius = 30;
                    chart.labelText = "[[title]]: [[value]]";
                } else {
                    chart.labelRadius = -30;
                    chart.labelText = "[[percents]]%";
                }
                chart.validateNow();
            }


            // makes chart 2D/3D                   
            function set3D() {
                if (document.getElementById("rb3").checked) {
                    chart.depth3D = 10;
                    chart.angle = 10;
                } else {
                    chart.depth3D = 0;
                    chart.angle = 0;
                }
                chart.validateNow();
            }

            // changes switch of the legend (x or v)
            function setSwitch() {
                if (document.getElementById("rb5").checked) {
                    legend.switchType = "x";
                } else {
                    legend.switchType = "v";
                }
                legend.validateNow();
            }
        </script>
    </head>
    
    <body>
    <div class='tema'><p><?php echo $tema; ?></p></div>
        <div id="chartdiv" style="width: 70%; height: 400px; margin:auto; background:#fff; box-shadow:0 0px 1px rgba(0,0,0, .7) inset,0 0px 2px rgba(0,0,0, .7); "></div>
        
       <!--<table align="center" cellspacing="0" style='box-shadow:0px; border:0px; border-top:0px; '>
            <tr>
                <td>
                    <input type="radio" checked="true" name="group" id="rb1" onclick="setLabelPosition()">labels outside
                    <input type="radio" name="group" id="rb2" onclick="setLabelPosition()">labels inside</td>
                <td>
                    <input type="radio" name="group2" id="rb3" onclick="set3D()">3D
                    <input type="radio" checked="true" name="group2" id="rb4" onclick="set3D()">2D</td>
                <td>Legend switch type:
                    <input type="radio" checked="true" name="group3" id="rb5"
                    onclick="setSwitch()">x
                    <input type="radio" name="group3" id="rb6" onclick="setSwitch()">v</td>
            </tr>
        </table>-->
<div style='margin:0 auto; margin-top:5px;text-align:left; width:90%; padding-left:120px;'><b>Total:</b> <?php echo $_GET['en_espera']+$_GET['aprobados']+$_GET['no_aprobados']+$_GET['en_elaboracion']+$_GET['finalizados']+$_GET['no_finalizados'];; ?></div>
<div class='papelera'><a href='?opcion=cproyecto'><img style='margin-top:-80px; width:20px; height:20px; right:6PX;' src='views/imagen/go-back.png'><br>Atrás</a></div>
    </body>

</html>
