<?php
if($_GET['opc']=='Residencia')
    {
    $tema='Estadísticas mensual de las constancias de residencia';
    $sql=" AND tipo='Residencia'";
    }
else if($_GET['opc']=='Buena conducta')
    {
    $tema='Estadísticas mensual de las constancias de buena conducta';
    $sql=" AND tipo='Buena conducta'";
    }
else if($_GET['opc']=='Bajos recursos')
    {
    $tema='Estadísticas mensual de las constancias de bajos recursos';
    $sql=" AND tipo='Bajos recursos'";
    }
else if($_GET['opc']=='Todas')
    {
    $tema='Estadísticas mensual de las constancias emitidas';
    $sql=";";
    }
$total=0;
for($i=1;$i<=12;$i++)
    {
    $mesConstancia=$constancia->consultarConstanciaPorMes($i,$sql,$_GET['anio']);
    echo "<input type='hidden' id='mes$i' value='$mesConstancia'>";
    $total+=$mesConstancia;
    }
?>
<input type='hidden' id='total_f' value='<?php echo $familias; ?>'>
<input type='hidden' id='total_p' value='<?php echo count($persona); ?>'>
<input type='hidden' id='ninios' value='<?php echo $ninios; ?>'>
<input type='hidden' id='adolecente' value='<?php echo $adolecente; ?>'>
<input type='hidden' id='adulto' value='<?php echo $adulto; ?>'>
<input type='hidden' id='adultoMayor' value='<?php echo $adultoMayor; ?>'>
<input type='hidden' id='femenino' value='<?php echo $femenino; ?>'>
<input type='hidden' id='masculino' value='<?php echo $masculino; ?>'>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title><?php echo $tema; ?></title>
        <link rel="stylesheet" href="style.css" type="text/css">
        <script src="libs/amcharts/amcharts/amcharts.js" type="text/javascript"></script>
        <script src="libs/amcharts/amcharts/serial.js" type="text/javascript"></script>
        <link rel='stylesheet' type='text/css' href='views/css/consultar.css'/>
        <script type="text/javascript">
            var ene=document.getElementById('mes1').value;
            var feb=document.getElementById('mes2').value;
            var mar=document.getElementById('mes3').value;
            var abr=document.getElementById('mes4').value;
            var may=document.getElementById('mes5').value;
            var jun=document.getElementById('mes6').value;
            var jul=document.getElementById('mes7').value;
            var ago=document.getElementById('mes8').value;
            var sep=document.getElementById('mes9').value;
            var oct=document.getElementById('mes10').value;    
            var nov=document.getElementById('mes11').value;    
            var dic=document.getElementById('mes12').value;
            var chart;
            var fecha = new Date();
            var anio=fecha.getFullYear();
            var chartData = [
                  {
                    "country": "Enero",
                    "visits": ene,
                    "color": "#FF0F00"
                },
                {
                    "country": "Febrero",
                    "visits": feb,
                    "color": "#FF6600"
                },
                {
                    "country": "Marzo",
                    "visits": mar,
                    "color": "#FF9E01"
                },
                {
                    "country": "Abril",
                    "visits": abr,
                    "color": "#FCD202"
                },
                {
                    "country": "Mayo",
                    "visits": may,
                    "color": "#F8FF01"
                },
                {
                    "country": "Junio",
                    "visits": jun,
                    "color": "#B0DE09"
                },
                {
                    "country": "Julio",
                    "visits": jul,
                    "color": "#04D215"
                },
                {
                    "country": "Agosto",
                    "visits": ago,
                    "color": "#0D8ECF"
                },
                {
                    "country": "Septiembre",
                    "visits": sep,
                    "color": "#0D52D1"
                },
                {
                    "country": "Octubre",
                    "visits": oct,
                    "color": "#2A0CD0"
                },
                {
                    "country": "Noviembre",
                    "visits": nov,
                    "color": "#8A0CCF"
                },
                {
                    "country": "Diciembre",
                    "visits": dic,
                    "color": "#CD0D74"
                }
            ];

            AmCharts.ready(function () {
                // SERIAL CHART
                chart = new AmCharts.AmSerialChart();
                chart.dataProvider = chartData;
                chart.categoryField = "country";
                chart.startDuration = 1;

                // AXES
                // category
                var categoryAxis = chart.categoryAxis;
                categoryAxis.labelRotation = 45; // this line makes category values to be rotated
                categoryAxis.gridAlpha = 0;
                categoryAxis.fillAlpha = 1;
                categoryAxis.fillColor = "#FAFAFA";
                categoryAxis.gridPosition = "start";

                // value
                var valueAxis = new AmCharts.ValueAxis();
                valueAxis.dashLength = 5;
                valueAxis.title = "Constancias del año "+anio;
                valueAxis.axisAlpha = 0;
                chart.addValueAxis(valueAxis);

                // GRAPH
                var graph = new AmCharts.AmGraph();
                graph.valueField = "visits";
                graph.colorField = "color";
                graph.balloonText = "<b>[[category]]: [[value]]</b>";
                graph.type = "column";
                graph.lineAlpha = 0;
                graph.fillAlphas = 1;
                chart.addGraph(graph);

                // CURSOR
                var chartCursor = new AmCharts.ChartCursor();
                chartCursor.cursorAlpha = 0;
                chartCursor.zoomable = false;
                chartCursor.categoryBalloonEnabled = false;
                chart.addChartCursor(chartCursor);

                chart.creditsPosition = "top-right";

                // WRITE
                chart.write("chartdiv");
            });
        </script>
    </head>

    <body>
    	<div class='tema'><p><?php echo $tema; ?></p></div>
        <div id="chartdiv" style="width: 90%; height: 400px; margin:auto; background:#fff; box-shadow:0 0px 1px rgba(0,0,0, .7) inset,0 0px 2px rgba(0,0,0, .7); "></div>
        <div style='margin:0 auto; margin-top:5px;text-align:left; width:90%; padding-left:05px;'><b>Total:</b> <?php echo $total; ?></div>
<div class='papelera' style='margin-top:-45px;' title='Atrás'><a href='?opcion=bconstancia'><img src='views/imagen/go-back.png'><br>Atrás</a></div>  
    </body>

</html>