<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    
    <head>
        <meta charset="utf-8">
        <title><?php echo $tema; ?></title>
        <script src="libs/amcharts/amcharts/amcharts.js" type="text/javascript"></script>
        <script src="libs/amcharts/amcharts/pie.js" type="text/javascript"></script>
        <link rel='stylesheet' type='text/css' href='views/css/consultar.css'/>
        <link rel='stylesheet' type='text/css' href='views/css/mensajes_validacion.css'/>
<?php
$sexo=$persona->consultarPersonaPorFecha($_GET['f_final'],$_GET['f_inicial']);
if(!$sexo)
    {
    echo $mensaje['not_reg_f'];
    header('refresh:4;?opcion=bstacfamilia');
    }
else
{
$f=0;$m=0;
for($i=0;$i<count($sexo);$i++)
    {
    if($sexo[$i]['sexo']=='F')
        $f++;
    else
        $m++;
    }
?>
<input type='hidden' id='f_' value="<?php echo $f; ?>">
<input type='hidden' id='m_' value="<?php echo $m; ?>">

        <script type="text/javascript">
            var chart;
            var legend;
            var f=document.getElementById('f_').value;
            var m=document.getElementById('m_').value;

            var chartData = 
            [{
                country: "Femenino",
                litres: f
            }, {
                country: "Masculino",
                litres: m

            }];

            AmCharts.ready(function () {
                // PIE CHART
                chart = new AmCharts.AmPieChart();
                chart.dataProvider = chartData;
                chart.titleField = "country";
                chart.valueField = "litres";

                // LEGEND
                legend = new AmCharts.AmLegend();
                legend.align = "center";
                legend.markerType = "circle";
                chart.balloonText = "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>";
                chart.addLegend(legend);

                // WRITE
                chart.write("chartdiv");
            });

            // changes label position (labelRadius)
            function setLabelPosition() {
                if (document.getElementById("rb1").checked) {
                    chart.labelRadius = 30;
                    chart.labelText = "[[title]]: [[value]]";
                } else {
                    chart.labelRadius = -30;
                    chart.labelText = "[[percents]]%";
                }
                chart.validateNow();
            }


            // makes chart 2D/3D                   
            function set3D() {
                if (document.getElementById("rb3").checked) {
                    chart.depth3D = 10;
                    chart.angle = 10;
                } else {
                    chart.depth3D = 0;
                    chart.angle = 0;
                }
                chart.validateNow();
            }

            // changes switch of the legend (x or v)
            function setSwitch() {
                if (document.getElementById("rb5").checked) {
                    legend.switchType = "x";
                } else {
                    legend.switchType = "v";
                }
                legend.validateNow();
            }
        </script>
    </head>
    
    <body>
    <div class='tema'><p><?php echo $tema; ?></p></div>
   <?php
    if($_GET['opc']=='votantes')
        {
		
   ?>
        <center><div style='margin:auto;text-aling:center; padding:3px 03px 03px 10px;width:55%; background:; font-weight:bold; margin-bottom:05px;'>Habitantes de la comunidad  con edades para votar</div></center>

    <?php
        }
    else if($_GET['opc']=='estadistica_p')  
        {  
        ?>
        <CENTER><div style='margin:auto;text-aling:center; width:50%; background:; font-weight:bold; margin-bottom:05px;'>Habitantes de la comunidad comprendido entre la edades de: <?php echo $_GET['edad_i']." a ".$_GET['edad_f']." años."; ?></div></CENTER>
        <?php
        }
        ?>
        <div id="chartdiv" style="width:60%; height: 350px; margin:auto; background:#fff; box-shadow:0 0px 1px rgba(0,0,0, .7) inset,0 0px 2px rgba(0,0,0, .7); "></div>     
 <div class='papelera' title='Atrás'><a href='?opcion=bstacfamilia'><img src='views/imagen/go-back.png'><br>Atrás</a></div>   
  <?php
     if($_GET['opc']=='votantes')
        {
        echo "<CENTER><div style='margin-top:-55px;'><a style='color:blue;'target='_blank' href='views/cvontantespdf_view.php'><img class='ico_op' src='views/imagen/document-pdf.png'></img> Cuaderno de votación</a></div></CENTER>";
        }
 ?>  
    </body>

</html>
<?php
}
?>