<!DOCTYPE html>
<html>
<head>
	<meta charset='utf-8'/>
	<title><?php echo $tema; ?></title>
		<link rel='stylesheet' type='text/css' href='views/css/mensajes_validacion.css'/>
	</head>
<body>
<?php
//print_r($_REQUEST['id']);
$vocero=$firmante->eliminarFirmanteVocero($_REQUEST['id']);
if($vocero)
	{
	echo $mensaje['eliminarf'];
	header("refresh:3;url=?opcion=inicio");
	}	
?>
</table>
</body>
</html>