<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<title><?php echo $tema; ?></title>
		<script type='text/javascript' src='views/js/funciones.js'></script>
		<link rel='stylesheet' type='text/css' href='views/css/mensajes_validacion.css'/>
		<link rel="stylesheet" href="views/css/pickmeup.css" type="text/css" />
		<script type="text/javascript" src="views/js/jquery.js"></script>
		<script type="text/javascript" src="views/js/jquery.pickmeup.js"></script>
		<script type="text/javascript" src="views/js/demo.js"></script>
		<link rel="stylesheet" type="text/css" href="views/css/estilo_formularios.css" />
	</head>
<body>
<?php
if($_SESSION['nivel_usuario']=='Administrador') //Validación de privilegios
{
$persona=$familia->consultarPersonaDni($_REQUEST['dni']);
$fecha=explode('-',$persona[0]['fecha_nac']);
$mostrarFormulario=true;
$validacion=true;
if(isset($_POST['actualizar'])) //Validación de lado del servidor
	{
	if($persona[0]['dni']==$_POST['dni_']&&$_GET['dni']!=$_POST['dni_'])
		echo $mensaje['dni_repeat'];
	else if(empty($_POST["nombre"])||strlen($_POST["nombre"])<2)
		echo $mensaje['name_real_wrong'];
	else if(empty($_POST["apellido"])||strlen($_POST["apellido"])<2)
		echo $mensaje['lastname_real_wrong'];	
	else if(empty($_POST["fecha_nac_m"]))
		echo $mensaje['not_birthday'];	
	else if(empty($_POST["sexo"]))
		echo $mensaje['not_sex'];
	else if(empty($_POST["parentesco"]))
		echo $mensaje['parent'];
	else if(empty($_POST["nivel_instruccion"]))
		echo $mensaje['niv_inst'];	
	else if(empty($_POST["anio_residencia"]))
		echo $mensaje['fecha_resid'];	
	else
		{
		$fallecido=($_POST['fallecido']==1)?1:0;
		$mudado=($_POST['mudado']==1)?1:0;
		//convirtiendo fecha a formato aaaa-mm-dd
		$fecha=$_POST['fecha_nac_m'];
		$fecha_m=explode("-",$fecha);
		$dia_m=$fecha_m[2];
		$mes_m=$fecha_m[1];
		$anio_m=$fecha_m[0];
		$fecha=$dia_m.'-'.$mes_m.'-'.$anio_m;
		//Guardadndo datos
		$res=$familia->actualizarPersona($persona[0]['id_p'],$_POST["tipo_dni"],$_POST["dni_"],$_POST["nombre"],$_POST["apellido"],$fecha,$_POST["sexo"],$_POST["parentesco"],$_POST["nivel_instruccion"],$_POST["habilidad_trabajo"],$_POST["profesion"],$_POST["enfermedad"],$_POST["discapacidad"],$_POST["anio_residencia"],$fallecido,$mudado);
		//Se actuaiza el estatus del vocero y usaurio dependiendo de la edición de la persona en si pertenece a la comunidad o no (atributo mudado)
		$estatus=($mudado=='1')?'0':'1';
		$r1=$familia->actualizarEstatusVoceroDependienteDePersona($_POST["dni_"],$estatus);
		$r2=$familia->actualizarEstatusUsuarioDependienteDePersona($_POST["dni_"],$estatus);

		//Se eliminar al estatus del vocero y usuario dependiendo de la edición de la persona; si ha fallecido o no (atributo fallecido)
		$elimina=($fallecido=='1')?'1':'0';
		$r1=$familia->eliminarEstatusVoceroDependienteDePersona($_POST["dni_"],$elimina);
		$r2=$familia->eliminarEstatusUsuarioDependienteDePersona($_POST["dni_"],$elimina);
		if($res)
			//Se gurda el movimiento que realia el usuario
			Historial::Movimiento($_SESSION['codigo'],"Actualizó a la persona de identificación: <b>".$_POST['dni_']."</b>");
		$mostrarFormulario=false;		
		}
	}
if($mostrarFormulario)
	{	
?>
	<div class='tema'><p><?php echo $tema; ?></p></div>

	<form id="form" name="form" method="POST" action="" >
	<table class='principal' cellspacing='15px' border='0' align='center'  style='margin-bottom:10px;'> 
		<tr>
			<td>Documento de identidad:<br>	
			<select name='tipo_dni' id='tipo_dni'>
				<option value='V' >V</option>
				<option value='E' >E</option>
			</select>
			<input class='input' value='<?php echo $persona[0]['dni']; ?>' type='text' maxlength='8' name='dni_' id='dni' placeholder='' class='input' onKeyPress='return validaSoloNumero(event);'></td>
			<td>Nombres:
				<br><input class='input' value='<?php echo $persona[0]['nombre']; ?>' type='text' maxlength='50' name='nombre' id='nombre' placeholder='' class='input' onKeyPress='return validaLetra(event);' > <label class='C_obligatorio'>*</label> 
			</td>
			<td>Apellidos:
				<br><input class='input' value='<?php echo $persona[0]['apellido']; ?>'  type='text' maxlength='50' name='apellido' id='apellido' placeholder='' class='input' onKeyPress='return validaLetra(event);' > <label class='C_obligatorio'>*</label></td>
			<td>Fecha de nacimiento:
			<br>
				<input value='<?php echo $fecha[2].'-'.$fecha[1].'-'.$fecha[0]; ?>'  type='text' class='datepicker' name='fecha_nac_m' readonly id='fecha_nac_m' size='20' placeholder='dd-mm-aaaa'/> <label class='C_obligatorio'>*</label>
			</td>
		</tr>
		<tr>
			<td>Sexo:<br>
			<select name='sexo' id='sexo'>
				<option value='0' >Seleccionar</option>
				<option value='F' <?php if($persona[0]['sexo']=='F') {?>selected <?php } ?>>Femenino</option>
				<option value='M' <?php if($persona[0]['sexo']=='M') {?>selected <?php } ?>>Masculino</option>
			</select> <label class='C_obligatorio'>*</label> 
			</td>
			<td>Parentesco:<br>
			<select name='parentesco' id='parentesco'>
				<option value='0'>Seleccionar</option>
				<option value='Abuel' <?php if($persona[0]['parentesco']=='Abuel') {?>selected <?php } ?> >Abuelo(a)</option>
				<option value='Padre' <?php if($persona[0]['parentesco']=='Padre') {?>selected <?php } ?>>Padre</option>
				<option value='Madre' <?php if($persona[0]['parentesco']=='Madre') {?>selected <?php } ?>>Madre</option>
				<option value='Espos' <?php if($persona[0]['parentesco']=='Espos') {?>selected <?php } ?>>Esposo(a)</option>
				<option value='Concubin' <?php if($persona[0]['parentesco']=='Concubin') {?>selected <?php } ?>>Concubino</option>
				<option value='Novi' <?php if($persona[0]['parentesco']=='Novi') {?>selected <?php } ?>>Novio(a)</option>				
				<option value='Herman' <?php if($persona[0]['parentesco']=='Herman') {?>selected <?php } ?>>Hermano(a)</option>
				<option value='Hij' <?php if($persona[0]['parentesco']=='Hij') {?>selected <?php } ?>>Hijo(a)</option>
				<option value='Tí' <?php if($persona[0]['parentesco']=='Tí') {?>selected <?php } ?>>Tío(a)</option>
				<option value='Sobrin' <?php if($persona[0]['parentesco']=='Sobrin') {?>selected <?php } ?>>Sobrino(a)</option>
				<option value='Prim' <?php if($persona[0]['parentesco']=='Prim') {?>selected <?php } ?>>Primo(a)</option>
				<option value='Niet' <?php if($persona[0]['parentesco']=='Niet') {?>selected <?php } ?>>Nieto(a)</option>
				<option value='Amig' <?php if($persona[0]['parentesco']=='Amig') {?>selected <?php } ?>>Amigo(a)</option>
				</select> <label class='C_obligatorio'>*</label> 
				</td>
			<td>Nivel de instrucción:<br>
			<select name='nivel_instruccion' id='nivel_instruccion'>
				<option value='0' >Seleccionar</option>
				<option value='Ninguno' <?php if($persona[0]['nivel_instruccion']=='Ninguno') {?>selected <?php } ?>>Ninguno</option>
				<option value='Básica' <?php if($persona[0]['nivel_instruccion']=='Básica') {?>selected <?php } ?>>Básica</option>
				<option value='Bachiller' <?php if($persona[0]['nivel_instruccion']=='Bachiller') {?>selected <?php } ?>>Bachiller</option>
				<option value='Técnico Medio' <?php if($persona[0]['nivel_instruccion']=='Técnico Medio') {?>selected <?php } ?>>Técnico Medio</option>
				<option value='Universitario' <?php if($persona[0]['nivel_instruccion']=='Universitario') {?>selected <?php } ?>>Universitario</option>
				<option value='Post Grado' <?php if($persona[0]['nivel_instruccion']=='Post Grado') {?>selected <?php } ?>>Post Grado</option>
				<option value='Doctorado' <?php if($persona[0]['nivel_instruccion']=='Doctorado') {?>selected <?php } ?>>Doctorado</option>
				<option value='PhD' <?php if($persona[0]['nivel_instruccion']=='PhD') {?>selected <?php } ?>>PhD</option>
			</select> <label class='C_obligatorio'>*</label> 
			</td>
				<td>Año de residencia:<br>
				<select name='anio_residencia'>
				<option value='0'>Seleccionar</option>
	<?php
			for($i=date('Y');$i>=date('Y')-100;$i--)
				{
	?>
				<option <?php if ($persona[0]['anio_residencia']==$i) {?>selected<?php } ?> value='<?php echo $i; ?>'><?php echo $i; ?></option>
	<?php
				}
	?>		</select> <label class='C_obligatorio'>*</label>
				</td>
				</tr>
				<tr>
					<td>Profesión u ocupación:
						<BR><input class='input' value='<?php echo $persona[0]['profesion']; ?>' size='20' type='text' maxlength='50' name='profesion' id='profesion' placeholder='Ej. Cajero del banco' onKeyPress='return validaLetra(event);' >
					</td>
					<td>Habilidad para el trabajo:
						<BR><input class='input' value='<?php echo $persona[0]['habilidad_trabajo']; ?>' size='20' type='text' maxlength='30' name='habilidad_trabajo' id='habilidad_trabajo' placeholder='Ej. Albañilería'  onKeyPress='return validaLetra(event);' >
					</td>
					<td colspan=''>Enfermedades:
						<BR><input class='input' value='<?php echo $persona[0]['enfermedad']; ?>' size='20' type='text' maxlength='50' name='enfermedad' id='enfermedad' placeholder='Ej. Obécidad, otra' onKeyPress='return validaLetra(event);' >
					</td>		
					<td colspan=''>Discapacidades:<br>
					&nbsp;&nbsp;&nbsp;
					<input <?php if(isset($persona[0]['p_discapacidad'])) { ?> checked <?php } ?>
					onClick="return preguntar_m('discapacidad');" type='radio' name='discapacid' value='Si'>Si
					&nbsp;&nbsp;&nbsp;
					<input <?php if(!isset($persona[0]['p_discapacidad'])) { ?> checked <?php } ?>
					onClick="return preguntar_n('discapacidad');" type='radio' name='discapacid' value='No' >No
					<label class='C_obligatorio'>*</label>
					<BR><input id='discapacidad' value="<?php echo $persona[0]['discapacidad']; ?>" type="text" maxlength="50" name="discapacidad" placeholder="Ej. Visual, otra" class='input' onKeyPress="return validaLetra(event);" style=''>
					</td>	
				</tr>
				<tr>
					<td colspan='2'><input type='checkbox' name='mudado' value='1' <?php if($persona[0]['mudado']==1) {?> checked <?php } ?> class='checkbox'> No pertenece a la comunidad</td>			
				</tr>				
				<tr>
					<td colspan='2'><input type='checkbox' name='fallecido' value='1' <?php if($persona[0]['fallecido']==1) {?> checked <?php } ?> class='checkbox'> Fallecida</td>			
				</tr>	
				<tr>
					<td colspan='4' style='text-align:center;'>
					<input style='margin-right:20px;' class='accion' type='reset' name='salir' value='Salir' onClick="if(confirm('¿Desea salir sin guardar los cambios?')) window.location='?opcion=inicio';">
					<input class='accion' type='submit' name='actualizar' value='Actualizar'>
					</td>
				</tr>
			</table>
<input type='hidden' value='<?php echo $_GET['id']; ?>' name='id'>			
<input type='hidden' value='<?php echo $persona[0]['dni']; ?>' name='dni'>
<input type='hidden' value='<?php echo $_GET['sector'];?>' name='sector'>
	</form>
<?php
	}
if(isset($res))
	{
	if($res)
		{
		echo $mensaje['updated'];
		header("refresh:2;url=?opcion=cgrupofamiliar&id=".$_GET['id']."&sector=".$_GET['sector']);
		}
	else
		{
		if(!$validacion)
			{
			$mensaje['error_updated'];
		//	header("refresh:3;url=?opcion=inicio");			
			}
		}
	}	
}
else
	echo $mensaje['not_privilege'];	
?>
</body>
</html> 