<?php 
{
?>
<!DOCTYPE html>
<html>
	<head>
			<meta charset="utf-8"/>
			<title><?php echo $tema; ?></title>
			<script type='text/javascript' src='views/js/funciones2.js'></script>
			<script type="text/javascript" src="views/js/chekear_usuario.js" ></script>
			<script type="text/javascript" src="views/js/chekear_dni.js" ></script>
			<!--<script type="text/javascript" src="views/js/chekear_email.js" ></script>-->
			<link rel="stylesheet" type="text/css" href="views/css/estilo_formularios.css" />
			<link rel='stylesheet' type='text/css' href='views/css/mensajes_validacion.css'/>
	</head>
<body onLoad='document.form.dni.focus();'>
<?php
// print_r($_POST);
$mostrarFormulario=true;
$validacion=false;

//Validando del lado de PHP
if(isset($_POST['enviar']))
	{
	$getUsuario=$usuario->consultarUsuarioPorDni($_POST['dni']);
	if(empty($_POST['dni']))
		echo "<center><div class='validacion' style='margin-right:265px; width:60%;'><img style='margin:0px;padding:0px;'src='views/imagen/exclamation.png'>&nbsp;&nbsp;Ingrese 
		el número del Documento de Identidad</div></center>";		
	else
		{
		//echo "Si (".$getUsuario[0]['dni_vocero']."==".$_POST['dni']."<br>";
		if($getUsuario[0]['dni_vocero']==$_POST['dni'])
			{
			$_SESSION['dni_r']=$_POST['dni'];
			$_SESSION['codigo_r']=$getUsuario[0]['id'];
			header('location:?opcion=recuperarclave');
			}
		else
			echo "<center><div class='validacion' style='margin-right:265px; width:60%;'><img style='margin:0px;padding:0px;'src='views/imagen/exclamation.png'>&nbsp;&nbsp;DISCULPE. El número del Documento de Identidad ingresado no pertenece a ningun usuario del sistema</div></center>";
		}
	}
if($mostrarFormulario)
{
?>
<div class='tema' style='margin-right:300px;'><p><?php echo $tema; ?></p></div>
<form class="principal" action="" method="POST" name='form' onSubmit='return validarCamposUsuario();'>
<table style='margin-right:415px;' class="principal" cellspacing="15px" border="0" align='center'>
	<tr>
		<td>Documento de Identidad:<br>
			<input class='input' style='width:150px;'id='dni' value="<?php if(!empty($_POST['dni'])) echo $_POST['dni']; ?>" type="text" size='14' maxlength="8" name='dni' class="input" onKeyPress="return validaSoloNumero(event);"  >
		</td>
	</tr>
	<tr style='text-align:center;'>
		<td><br><input class='accion' type='submit' name='enviar' value='Continuar'></td>
	</tr>
	</table>
</form>
<?php
}
if(isset($res))
	{
	if($res)
		{
		echo $mjs['envio'];
		header("refresh:2;url=?opcion=inicio");
		}
	else
		{
		if(!$validacion)
			{
			echo $msj['error'];
			header("refresh:3;url=?opcion=inicio");			
			}
		}
	}
?>
</body>
</html>
<?php
}
?>
