<?php

?>
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
	<title><?php echo $tema; ?></title>
<link rel='stylesheet' type='text/css' href='views/css/consultar.css'/>
<script type='text/javascript' src='views/js/funciones.js'></script>
</head>
<body>
<div class='tema'>
<label class='titulo'><?php echo $tema; ?></label>
</div>
<?php

//Mostrar todos los movimientos registrados por los usuarios
?>
	<table cellspacing='02' class='principal'>
	<tr style='text-align:center;' >
		<th><a href='#'>Acción realizada</a></th>
		<th><a href='#'>Fecha</a></th>
		<th class='ultima'><a href='#'>Hora</a></th>
		<!--<th>Detalles</th>-->
	</tr>
<?php
//Mostrar información de los departamentos registrados.
for($i=0;$i<count($lista);$i++)
	{
	//Convertir fecha YY-MM-DD a DD-MM-YY.
	$fecha=$lista[$i]['fecha'];
	$fecha_m=explode("-",$fecha);
	$dia_m=$fecha_m[2];
	$mes_m=$fecha_m[1];
	$anio_m=$fecha_m[0];
	$fecha_reg=$dia_m.'-'.$mes_m.'-'.$anio_m;
//	$nombre=$inst->ConsultarNombreInst($movimiento[$i]['id_departamento']);
?>
	<tr style='text-align:center;'  id="<?php echo "id_$i"; ?>" onMouseMove="cambiarColor('<?php echo "id_$i"; ?>','#FAFAFA url(imagenes/background.png) repeat-x 0 -10px');" onMouseOut="cambiarColor('<?php echo "id_$i"; ?>','#fff');" >
	
		<td style='text-align:center;'><?php echo $lista[$i]['accion']; ?></td>
		<td><?php echo $fecha_reg; ?></td>
		<td class='ultima'><?php echo $lista[$i]['hora']; ?></td>
<!--	<td><?php //  ?>Detalles</td>-->
	</tr>
<?php
	}
?>
	</table>
<!-- FUENTE: www.CesarCancino.com -->
<div class='paginador' align='center' >
<ul>
	<li style="display:inline; margin-right:6px;">
	<?php if($params['primero']):	?>
		<a  class='parametro'  href="?opcion=<?php echo $opcion; ?>&pagina=<?php echo $params['primero']; ?>">
		Primero
		</a>
	<?php	else: ?>
		Primero
	<?php	endif; ?>
	
	</li>
	<li style="display:inline; margin-right:6px;">
	<?php if($params['anterior']):	?>
		<a  class='parametro'  href="?opcion=<?php echo $opcion; ?>&pagina=<?php echo $params['anterior']; ?>">
		Anterior
		</a>
	<?php	else: ?>
		Anterior
	<?php	endif; ?>
	</li>
	<!--<li style="display:inline; margin-right:6px;">
	<?php for($i=1;$i<=$params['total'];$i++) {?>
	<?php if($params['actual']!=$i):	?>
		<a  class='parametro'  href="?pagina=<?php echo $i; ?>">
		<?php echo $i; ?>
		</a>
	<?php	else: ?>
		<?php echo $i; ?>
	<?php	endif; ?>
	<?php } ?>
	</li>-->
	<li style="display:inline; margin-right:6px;">
	<?php if($params['siguiente']):	?>
		<a  class='parametro'  href="?opcion=<?php echo $opcion; ?>&pagina=<?php echo $params['siguiente']; ?>">
		Siguiente
		</a>	
	<?php	else: ?>
		Siguiente
	<?php	endif; ?>
	</li>
	</li>
	<li style="display:inline; margin-right:5px;">
	<?php if($params['ultimo']):	?>
		<a  class='parametro'  class='parametro' href="?opcion=<?php echo $opcion; ?>&pagina=<?php echo $params['ultimo']; ?>">
		Último
		</a>
	<?php	else: ?>
		Último
	<?php	endif; ?>
	</li>
</ul>
</div>
</body>
</html>