<?php
unset($_SESSION['nueva_familia']);
?>
<!doctype html>
<html>
	<title>Bienvenido a SIGAF</title>
<head>
	<meta charset="utf-8" />
	<link rel='stylesheet' type='text/css' href='views/css/bienvenida.css'/>
</head>
<body>
<div id='general'>
<center><b><?php echo $tema; ?></b></center>
<BR>

<label style='text-align:justify;'>
<p>
Promover y consolidar la democracia participativa y protagónica, a través de los procesos de desarrollo social, local y comunitario, logrando así
generar nuevos conocimientos colectivos, que permitan la elaboración y gestión de estrategias para la articulación de comunidades y redes sociales en torno al nuevo proyecto de la sociedad.

</p>

<p>

</div>
</body>
</html>

