<?php 
{
$getUsuario=$usuario->consultarUsuarioPorDni($_SESSION['dni_r']);

?>
<!DOCTYPE html>
<html>
	<head>
			<meta charset="utf-8"/>
			<title><?php echo $tema; ?></title>
			<script type='text/javascript' src='views/js/funciones2.js'></script>
			<script type="text/javascript" src="views/js/chekear_usuario.js" ></script>
			<script type="text/javascript" src="views/js/chekear_dni.js" ></script>
			<!--<script type="text/javascript" src="views/js/chekear_email.js" ></script>-->
			<link rel="stylesheet" type="text/css" href="views/css/estilo_formularios.css" />
			<link rel='stylesheet' type='text/css' href='views/css/mensajes_validacion.css'/>
	</head>
<body onLoad='document.form.dni.focus();'>
<?php
// print_r($_POST);
$mostrarFormulario=true;
$validacion=false;
//Validando del lado de PHP
if(isset($_POST['enviar']))
	{
	if(empty($_POST['respuesta_secreta']))
		echo "<center><div class='validacion' style='margin-right:265px; width:60%;'><img style='margin:0px;padding:0px;'src='views/imagen/exclamation.png'>&nbsp;&nbsp;Ingrese la respuesta secreta de seguridad</div></center>";		
	else
		{
		if($getUsuario[0]['respuesta_secreta']==md5($_POST['respuesta_secreta']))
			header('location:?opcion=nuevaclave');
		else
			echo "<center><div class='validacion' style='margin-right:265px; width:60%;'><img style='margin:0px;padding:0px; 'src='views/imagen/exclamation.png'>&nbsp;&nbsp;Respuesta secreta incorrecta</div></center>";	
		/*if($res)
			{
			Historial::Movimiento($_SESSION['codigo'],"Registró al usuario <b>".$_POST['nombre_usuario']."</b>");
			$mjs['envio']="<center><div class='mensaje_envio'>El usuario se registró correctamente</div></center>";
			$mostrarFormulario=false;				
			}
		else
			{
			$msj['error']="<center><div class='validacion'><img style='margin:0px;padding:0px;'src='views/imagen/exclamation.png'>&nbsp;&nbsp;Problemas para registrar el usuario. Contacte a su administrador de sistema</div></center>";
			$mostrarFormulario=false;	
			}*/
		}
	}
if($mostrarFormulario)
{
?>
<div class='tema' style='margin-right:300px;'><p><?php echo $tema; ?></p></div>
<form class="principal" action="" method="POST" name='form' onSubmit='return validarCamposUsuario();'>
<table style='margin-right:325px;' class="principal" cellspacing="15px" border="0" align='center'>
	<tr>
		<td colspan='2'>Pregunta secreta:</BR><input readonly class='input' style='width:325px;' value="<?php echo $getUsuario[0]['pregunta_secreta']; ?>" type="text" maxlength="50" name="pregunta_secreta" id='pregunta_secreta' onKeyPress="return validaLetra(event);" ></td>
	</tr>
	<tr>
		<td colspan='2'>Respuesta secreta:<br> <input class='input' style='width:325px;' value="<?php if(!empty($_POST['respuesta_secreta'])) echo $_POST['respuesta_secreta']; ?>" type="text" maxlength="20" name="respuesta_secreta" id='respuesta_secreta' onKeyPress="return validaLetra(event);" ></td>
	</tr>
	<tr style='text-align:center;'>
		<td colspan='2' ><br><input style='margin-right:10px;' class='accion' type='submit' name='enviar' value='Continuar'></td>
	</tr>
	</table>
</form>
<?php
}
if(isset($res))
	{
	if($res)
		{
		echo $mjs['envio'];
		header("refresh:2;url=?opcion=inicio");
		}
	else
		{
		if(!$validacion)
			{
			echo $msj['error'];
			header("refresh:3;url=?opcion=inicio");			
			}
		}
	}
?>
</body>
</html>
<?php
}
?>