<?php
unset($_SESSION['nueva_familia']);
?>
<!doctype html>
<html>
	<title>Bienvenido a SIGAF</title>
<head>
	<meta charset="utf-8" />
	<link rel='stylesheet' type='text/css' href='views/css/bienvenida.css'/>
</head>
<body>
<div id='general'>
<center><b><?php echo $tema; ?></b></center>
<BR>

<label style='text-align:justify;'>
<p>
Generar un cambio democrático en la comunidad que propicie un desarrollo armónico local, logrando elevar el espíritu y nivel de sus habitantes del Consejo Comunal Punta  rava, La Poza y Los Primos; garantizando la seguridad, solidez, dinamismo, sustentabilidad, permanencia y equidad, en el crecimiento de la economía comunal a través de una planificación estratégica consolidando las tomas de decisiones de forma abierta, en un ambiente de sana paz y ética como las refleja la ley de los consejos comunales.

</p>

</div>
</body>
</html>

